apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlapp-ds3
  template: # Definimos la plantilla de los pods
    metadata:
      labels:
        app: mlapp-ds3 # Cada pod tendrá esta etiqueta
    spec:
      containers:
        - name: mlapp-ds3-container # Nombre del contenedor
          image: ghcr.io/juanloaiza007/mlapp-ds3:1.0
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: mlapp-service
spec:
  selector:
    app: mlapp-ds3
  ports:
    - protocol: TCP
      port: 80 # Puerto interno del servicio
      targetPort: 8000 # Puerto del pod al que redirige el tráfico
      nodePort: 30080 # Puerto externo del servicio (accesible mediante el navegador)
  type: NodePort
